services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=price_tracker
      - POSTGRES_USER=price_tracker
      - POSTGRES_PASSWORD=price_tracker

  app:
    build: .
    command: python price_tracker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
